### ISSUE TITLE
How do you use it?

### ISSUE THREAD

**Issue by brabalan** [zsugabubus/interception-k2k#1]
I tried using this plugin, and I cannot make it work. Here is what I did:

```
make CONFIG_DIR=example
make CONFIG_DIR=example install
```

then I edited `/etc/udevmon.yaml ` to be
```
- JOB: "intercept -g $DEVNODE | /opt/interception/interception-pipe0 | uinput -d $DEVNODE"
  DEVICE:
    EVENTS:
      EV_KEY: [KEY_CAPSLOCK, KEY_ESC]
```

and I finally did `sudo systemctl restart udevmon.service`

What I observe:
- caps lock is bound to ctrl_l, even by itself
- escape stays escape
- ctrl_l is bound to caps lock

According to https://gitlab.com/interception/linux/plugins/caps2esc/issues/9#note_202408489 it should work out of the box. Am I doing something wrong?
