### ISSUE TITLE
broken configuration for multitple keyboards

### ISSUE THREAD

**Issue by brabalan** [zsugabubus/interception-k2k#3]
I have the following configuration:

```yaml
- JOB: "intercept -g $DEVNODE | /opt/interception/interception-ergo | uinput -d $DEVNODE"
  DEVICE:
    NAME: "TrulyErgonomic.com Truly Ergonomic Computer Keyboard"
    EVENTS:
      EV_KEY: [KEY_CAPSLOCK, KEY_ESC]
- JOB: "intercept -g $DEVNODE | /opt/interception/interception-dell | uinput -d $DEVNODE"
  DEVICE:
    NAME: "AT Translated Set 2 keyboard"
    EVENTS:
      EV_KEY: [KEY_CAPSLOCK, KEY_ESC]
```

with the following tap-rules.h.in for dell
```c
{ .base_key = KEY_CAPSLOCK, .tap_key = KEY_ESC, .repeat_key = KEY_LEFTCTRL, .hold_key = KEY_LEFTCTRL },
{ .base_key = KEY_APOSTROPHE, .tap_key = KEY_APOSTROPHE, .repeat_key = KEY_RIGHTCTRL, .hold_key = KEY_APOSTROPHE },
```
and for the ergo external keyboard
```c
{ .base_key = KEY_CAPSLOCK, .tap_key = KEY_ESC, .repeat_key = KEY_LEFTCTRL, .hold_key = KEY_LEFTCTRL },
{ .base_key = KEY_RIGHTCTRL, .tap_key = KEY_APOSTROPHE, .repeat_key = KEY_APOSTROPHE, .hold_key = KEY_RIGHTCTRL },
```

Everything works with the internal dell keyboard, but it does not with the ergo one: I get an unconditional `ESC` on the caps lock key, and `'` on the right control key (even when holding the key). Did something change when you introduced the tapping rules?
